## Q1

In [1]:
import numpy as np

arr = np.arange(1, 13)  

arr_2d = arr.reshape(3, 4)

print("数组的维度(ndim):", arr_2d.ndim)
print("数组的形状(shape):", arr_2d.shape)
print("数组的元素总个数(size):", arr_2d.size)


数组的维度(ndim): 2
数组的形状(shape): (3, 4)
数组的元素总个数(size): 12


## Q2

In [2]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7, 4.8])

print("转换前的数组：", arr)
print("转换前的数据类型：", arr.dtype.name)

arr_int = arr.astype(np.int32)

print("转换后的数组：", arr_int)
print("转换后的数据类型：", arr_int.dtype.name)


转换前的数组： [1.5 2.6 3.7 4.8]
转换前的数据类型： float64
转换后的数组： [1 2 3 4]
转换后的数据类型： int32


## Q3

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

sub_arr = arr[:2, 1:3]

print(sub_arr)


[[2 3]
 [6 7]]


## Q4

In [5]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30, 35])

fancy = arr[[0, 2, 4]]
print("花式索引结果：", fancy)

bool_idx = arr > 20
bool_res = arr[bool_idx]
print("布尔索引（大于20）：", bool_res)

花式索引结果： [10 20 30]
布尔索引（大于20）： [25 30 35]


## Q5

In [ ]:
import numpy as np

arr_a = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])

result = arr_a + arr_b
print("广播相加结果：")
print(result)

广播相加结果：
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## Q6

In [ ]:
import numpy as np

x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

sqrt_x = np.sqrt(x)
print("x的平方根：", sqrt_x)

max_xy = np.maximum(sqrt_x, y)
print("对应位置最大值：", max_xy)

x的平方根： [1. 2. 3. 4.]
对应位置最大值： [2. 2. 4. 5.]


## Q7

In [5]:
import numpy as np

arr = np.arange(24).reshape((2, 3, 4))

arr_T = arr.transpose((1, 0, 2))

print("转置后数组形状：", arr_T.shape)

转置后数组形状： (3, 2, 4)


## Q8

In [ ]:
import numpy as np

arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])

cond = np.array([True, False, True])

result = np.where(cond, arr_x, arr_y)
print("条件逻辑运算结果：", result)

条件逻辑运算结果： [1 6 7]


## Q9

In [14]:
import numpy as np

arr = np.array([[6, 2, 7], [3, 6, 2], [2, 4, 3]])

mean_all = arr.mean()
print("所有元素平均值：", mean_all)

arr_sorted = np.sort(arr, axis=0)
print("沿axis=0排序后的数组：")
print(arr_sorted)

所有元素平均值： 3.888888888888889
沿axis=0排序后的数组：
[[2 2 2]
 [3 4 3]
 [6 6 7]]


## Q10

In [4]:
import numpy as np

np.random.seed(10)

A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

dot_result = np.dot(A, B)

print("矩阵A：")
print(A)
print("\n矩阵B：")
print(B)
print("\nA·B 矩阵点积：")
print(dot_result)

矩阵A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

矩阵B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

A·B 矩阵点积：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]


In [8]:
import numpy as np
np.random.seed(5)
A=np.random.rand(2,2)
print(A)



[[0.22199317 0.87073231]
 [0.20671916 0.91861091]]
